export const LocationConstants = {
	REQUEST_LOCATIONS: "REQUEST_LOCATIONS",
	RECEIVE_LOCATIONS: "RECEIVE_LOCATIONS",
	SET_DETAIL: "SET_DETAIL",
	SET_BOUNDS: "SET_BOUNDS",
	SET_QUERIES: "SET_QUERIES"
};