export const LocationConstants = {
	REQUEST_LOCATIONS: "REQUEST_LOCATIONS",
	RECEIVE_LOCATIONS: "RECEIVE_LOCATIONS",
	SET_DETAIL: "SET_DETAIL",
	SET_BOUNDS: "SET_BOUNDS",
	SET_QUERIES: "SET_QUERIES",
	SET_QUERY_FIELD: "SET_QUERY_FIELD",
	REQUEST_SUGGESTIONS: "REQUEST_SUGGESTIONS",
	PICK_SUGGESTION: "PICK_SUGGESTION",
	RECEIVE_SUGGESTIONS: "RECEIVE_SUGGESTIONS",
	CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS"
};